[project]
name = "pyssg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "bibtexparser>=1.4.3",
    "jinja2>=3.1.6",
    "markdown-it-py>=3.0.0",
    "pygments>=2.19.1",
    "pyyaml>=6.0.2",
    "watchdog>=6.0.0",
]
